version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8000
    volumes:
      - .:/app
    command: >
      bash -c "python manage.py makemessages -a && python manage.py compilemessages && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
